{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
{{ include "metabase.labels" . | indent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  MB_DB_PASS: {{ .Values.secrets.metabaseDbPasswd | default (randAlphaNum 32) | b64enc | quote  }}
  MB_ENCRYPTION_SECRET_KEY: {{ .Values.secrets.secretKey | default (randAlphaNum 32) | b64enc | quote }}
{{ end }}
