apiVersion: v1
kind: Secret
metadata:
  name: k8s-ldap-passwd-binduser-secret
  labels:
    app.kubernetes.io/name: {{ include "ltb-passwd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  BINDDN: {{ .Values.secrets.binddn | b64enc }}
  BINDPW: {{ .Values.secrets.bindpw | b64enc }}
